#ifndef CODIGOS_HPP
#define CODIGOS_HPP

#define SERVIDOR_CONFIRMA_CONEXION 0X01
#define SERVIDOR_RECHAZA_CONEXION 0X02
#define SERVIDOR_LLENO 0X03
#define SERVIDOR_DESCONECTA_CLIENTE 0x08
#define SERVIDOR_PIDE_LETRA 0x10
#define SERVIDOR_ENVIA_PALABRA 0x11
#define SERVIDOR_ENVIA_JUGADA 0x12
#define SERVIDOR_FIN_PARTIDA 0X13
#define SERVIDOR_FIN_FORZADO 0X14
#define CLIENTE_CONECTADO 0x20
#define CLIENTE_LISTO_PARA_EMPEZAR 0x21
#define CLIENTE_ENVIA_LETRA 0x22
#define CLIENTE_ESPERA_TURNO 0x23
#define CLIENTE_DESCONECTA 0x30
#define TIEMPO_EXPIRADO 0x31
#define CARACTER_INVALIDO 0x32

#endif